SELECT mg.GENRE, COUNT(mg.GENRE) AS MOVIE_COUNT
FROM MOVIES_GENRES AS mg
GROUP BY mg.GENRE
HAVING COUNT(mg.GENRE) = (
    SELECT MAX(MOVIE_COUNT)
    FROM (
        SELECT COUNT(GENRE) AS MOVIE_COUNT
        FROM MOVIES_GENRES
        GROUP BY GENRE
    ) AS subquery
)
ORDER BY GENRE
